/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package subrenamer;

import java.io.File;
import javax.swing.JFileChooser;

/**
 *
 * @author Ciambellano
 */
public class InterfacciaGrafica extends javax.swing.JFrame {

    /**
     * Creates new form interfacciaGrafica
     */
    public InterfacciaGrafica() {
        initComponents();
        
        //questa riga mette la finestra al centro dello schermo
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        finestraScegliFile = new javax.swing.JFileChooser();
        testoScegliFile = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        finestraScegliFile.setFileSelectionMode(javax.swing.JFileChooser.FILES_AND_DIRECTORIES);
        finestraScegliFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finestraScegliFileActionPerformed(evt);
            }
        });

        testoScegliFile.setText("Selezionare la cartella in cui si trovano sottotitoli e file video:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(finestraScegliFile, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(testoScegliFile))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(testoScegliFile)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(finestraScegliFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void finestraScegliFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finestraScegliFileActionPerformed

        if(evt.getActionCommand().equals(javax.swing.JFileChooser.APPROVE_SELECTION)){
            File directorySelezionata = finestraScegliFile.getSelectedFile();
            
            //se non c'è specificato un file prende il percorso della directory in cui si trova il file jar
            String percorsoFile = ".";
            
            if (directorySelezionata.isDirectory()) {
                percorsoFile = directorySelezionata.getPath();
            } else if(directorySelezionata.isFile()){
                percorsoFile = directorySelezionata.getAbsolutePath();
            }
            
            Rinominatore rinominatore = new Rinominatore(percorsoFile);
        }
        else if(evt.getActionCommand().equals(javax.swing.JFileChooser.CANCEL_SELECTION)){
            System.exit(0);
        }
    }//GEN-LAST:event_finestraScegliFileActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfacciaGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfacciaGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfacciaGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfacciaGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfacciaGrafica().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser finestraScegliFile;
    private javax.swing.JLabel testoScegliFile;
    // End of variables declaration//GEN-END:variables
}
